//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lua_generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lua_generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include(&quot;shared.lua&quot;)
        ///
        ///function ENT:Initialize()
        ///end
        ///
        ///function ENT:Draw()
        ///	self:DrawModel()
        ///end
        ///
        ///function ENT:DrawTranslucent()
        ///	self:Draw()
        ///end
        ///
        ///function ENT:Think()
        ///end.
        /// </summary>
        internal static string cl_init {
            get {
                return ResourceManager.GetString("cl_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCSLuaFile(&quot;cl_init.lua&quot;)
        ///AddCSLuaFile(&quot;shared.lua&quot;)
        ///include(&quot;shared.lua&quot;)
        ///
        ///function ENT:Initialize()
        ///	self:SetModel(&quot;models/props_borealis/bluebarrel001.mdl&quot;)
        ///	self:PhysicsInit(SOLID_VPHYSICS)
        ///	self:SetMoveType(MOVETYPE_VPHYSICS)
        ///	self:SetUseType(SIMPLE_USE)
        ///	self:DropToFloor()
        ///
        ///	local phys = self:GetPhysicsObject()
        ///	if phys:IsValid() then
        ///		phys:Wake()
        ///	end
        ///end
        ///
        ///function ENT:SpawnFunction(ply, tr, class)
        ///	if not tr.Hit then return end
        ///	
        ///	local SpawnAng = ply:EyeAngles()
        ///	SpawnAng.p  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init {
            get {
                return ResourceManager.GetString("init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENT.Type = &quot;anim&quot;
        ///ENT.Base = &quot;base_gmodentity&quot;
        ///
        ///ENT.PrintName    = &quot;Entity Generator&quot;
        ///ENT.Author       = &quot;LUA GENERATOR&quot;
        ///ENT.Contact      = &quot;n/a&quot;
        ///ENT.Category     = &quot;lua Generator&quot;
        ///ENT.Purpose      = &quot;Description&quot;
        ///ENT.Instructions = &quot;Instruction&quot;
        ///
        ///ENT.Spawnable = true
        ///ENT.AdminOnly = true
        ///
        ///--ENT.RenderGroup = RENDERGROUP_BOTH
        ///
        ///function ENT:SetupDataTables()
        ///	--self:NetworkVar(&quot;Entity&quot;, 0, &quot;owning_ent&quot;)
        ///end
        ///
        ///function ENT:PhysicsUpdate(phys)
        ///end.
        /// </summary>
        internal static string shared {
            get {
                return ResourceManager.GetString("shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWEP.Base                  = &quot;weapon_base&quot;
        ///SWEP.Category              = &quot;lua Generator&quot;
        ///SWEP.PrintName             = &quot;lua Generator&quot;
        ///SWEP.Spawnable             = true
        ///SWEP.AdminOnly             = true
        ///
        ///SWEP.Author                = &quot;n/a&quot;
        ///SWEP.Contact               = &quot;n/a&quot;
        ///SWEP.Purpose               = &quot;n/a&quot;
        ///SWEP.Instructions          = &quot;Description&quot;
        ///
        ///SWEP.ViewModel             = &quot;models/weapons/v_pistol.mdl&quot;
        ///SWEP.WorldModel            = &quot;models/weapons/w_pistol.mdl&quot;
        ///SWEP.ViewModelFOV          = 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weapon_source {
            get {
                return ResourceManager.GetString("weapon_source", resourceCulture);
            }
        }
    }
}
